// PPE icon keys used in checklist items
export const PPE_ICONS = {
  mask: { label: 'Mask', hi: 'मास्क', icon: '😷' },
  gloves: { label: 'Gloves', hi: 'दस्ताने', icon: '🧤' },
  boots: { label: 'Boots', hi: 'जूते', icon: '🥾' },
  coverall: { label: 'Coverall', hi: 'कवरऑल', icon: '🦺' },
  seatbelt: { label: 'Seatbelt', hi: 'सीटबेल्ट', icon: '🪢' },
  goggles: { label: 'Goggles', hi: 'चश्मा', icon: '🥽' },
  helmet: { label: 'Helmet', hi: 'हेलमेट', icon: '⛑️' },
}

const TEMPLATES = [
  {
    id: 'pesticide',
    icon: 'pesticide',
    title: { en: 'Pesticide Application Safety', hi: 'कीटनाशक छिड़काव सुरक्षा' },
    description: {
      en: 'Complete safety checklist before pesticide spraying',
      hi: 'कीटनाशक छिड़काव से पहले पूर्ण सुरक्षा जांच सूची',
    },
    estimatedMinutes: 15,
    items: [
      {
        id: 1,
        emoji: '🧤🥽',
        en: 'Wear full PPE: mask, gloves, boots, long-sleeved clothing',
        hi: 'पूर्ण PPE पहनें: मास्क, दस्ताने, जूते, लंबी आस्तीन के कपड़े',
        ppe: ['mask', 'gloves', 'goggles', 'boots', 'coverall'],
      },
      {
        id: 2,
        emoji: '📋',
        en: 'Read and verify pesticide label instructions carefully',
        hi: 'कीटनाशक लेबल निर्देशों को ध्यान से पढ़ें और सत्यापित करें',
        ppe: [],
      },
      {
        id: 3,
        emoji: '⚗️🧪',
        en: 'Verify pesticide mixing ratios per label instructions',
        hi: 'लेबल निर्देशों के अनुसार कीटनाशक मिश्रण अनुपात सत्यापित करें',
        ppe: ['gloves', 'goggles'],
      },
      {
        id: 4,
        emoji: '🌿💨',
        en: 'Check spray equipment for leaks and proper function',
        hi: 'लीक और उचित कार्य के लिए स्प्रे उपकरण की जांच करें',
        ppe: ['gloves'],
      },
      {
        id: 5,
        emoji: '🧼🚿',
        en: 'Wash hands and face thoroughly after application',
        hi: 'छिड़काव के बाद हाथ और चेहरा अच्छी तरह धोएं',
        ppe: [],
      },
      {
        id: 6,
        emoji: '🏪🔒',
        en: 'Store pesticides in locked, ventilated area away from food',
        hi: 'कीटनाशकों को बंद, हवादार जगह पर खाने से दूर रखें',
        ppe: [],
      },
      {
        id: 7,
        emoji: '🩹⛑️',
        en: 'Keep first aid kit nearby and know emergency contacts',
        hi: 'प्राथमिक चिकित्सा किट पास रखें और आपातकालीन नंबर जानें',
        ppe: [],
      },
      {
        id: 8,
        emoji: '🗑️♻️',
        en: 'Dispose of empty containers safely — do not reuse',
        hi: 'खाली कंटेनर सुरक्षित रूप से निपटाएं — पुन: उपयोग न करें',
        ppe: ['gloves'],
      },
    ],
  },
  {
    id: 'tractor',
    icon: 'tractor',
    title: { en: 'Tractor/Machinery Operation', hi: 'ट्रैक्टर/मशीनरी संचालन' },
    description: {
      en: 'Pre-operation safety inspection for tractors and machinery',
      hi: 'ट्रैक्टर और मशीनरी के लिए संचालन-पूर्व सुरक्षा निरीक्षण',
    },
    estimatedMinutes: 10,
    items: [
      {
        id: 1,
        emoji: '🔍🔧',
        en: 'Check tire pressure and condition',
        hi: 'टायर प्रेशर और स्थिति जांचें',
        ppe: ['gloves'],
      },
      {
        id: 2,
        emoji: '⛽🔥',
        en: 'Verify fuel and oil levels',
        hi: 'ईंधन और तेल का स्तर जांचें',
        ppe: ['gloves'],
      },
      {
        id: 3,
        emoji: '🪢',
        en: 'Wear seatbelt during operation',
        hi: 'संचालन के दौरान सीटबेल्ट पहनें',
        ppe: ['seatbelt', 'helmet'],
      },
      {
        id: 4,
        emoji: '💡🚨',
        en: 'Check lights and signals are working',
        hi: 'लाइट और सिग्नल काम कर रहे हैं जांचें',
        ppe: [],
      },
      {
        id: 5,
        emoji: '🛑',
        en: 'Test brakes before operation',
        hi: 'संचालन से पहले ब्रेक टेस्ट करें',
        ppe: [],
      },
      {
        id: 6,
        emoji: '🩹⛑️',
        en: 'Keep first aid kit accessible',
        hi: 'प्राथमिक चिकित्सा किट पहुंच में रखें',
        ppe: [],
      },
      {
        id: 7,
        emoji: '🛡️',
        en: 'Ensure all safety guards and rollover protection are in place',
        hi: 'सभी सुरक्षा गार्ड और रोलओवर प्रोटेक्शन सही जगह हैं सुनिश्चित करें',
        ppe: ['helmet'],
      },
      {
        id: 8,
        emoji: '🅿️',
        en: 'Inspect hydraulic system for leaks before parking',
        hi: 'पार्किंग से पहले लीक के लिए हाइड्रोलिक सिस्टम की जांच करें',
        ppe: ['gloves'],
      },
    ],
  },
  {
    id: 'harvesting',
    icon: 'harvesting',
    title: { en: 'Harvesting Safety', hi: 'फसल कटाई सुरक्षा' },
    description: {
      en: 'Safety checklist for manual and machine harvesting operations',
      hi: 'हाथ और मशीन से फसल कटाई के लिए सुरक्षा जांच सूची',
    },
    estimatedMinutes: 15,
    items: [
      {
        id: 1,
        emoji: '🌤️📋',
        en: 'Check weather conditions — avoid harvesting during storms or extreme heat',
        hi: 'मौसम की जांच करें — तूफान या भीषण गर्मी में कटाई न करें',
        ppe: [],
      },
      {
        id: 2,
        emoji: '🔪🔧',
        en: 'Inspect harvesting tools — sickle sharpness, combine harvester condition',
        hi: 'कटाई के औज़ारों की जांच करें — दरांती की धार, हार्वेस्टर की हालत',
        ppe: ['gloves'],
      },
      {
        id: 3,
        emoji: '👕🥾',
        en: 'Wear proper clothing — long sleeves, sturdy boots, sun hat',
        hi: 'सही कपड़े पहनें — लंबी आस्तीन, मज़बूत जूते, टोपी',
        ppe: ['boots', 'gloves', 'helmet'],
      },
      {
        id: 4,
        emoji: '💧⏱️',
        en: 'Carry sufficient water — drink every 30 minutes, take regular breaks',
        hi: 'पर्याप्त पानी साथ रखें — हर 30 मिनट में पानी पिएं, नियमित आराम करें',
        ppe: [],
      },
      {
        id: 5,
        emoji: '🐍🦂',
        en: 'Watch for snakes, scorpions, and insects hiding in crop fields',
        hi: 'खेत में छिपे सांप, बिच्छू और कीड़ों से सावधान रहें',
        ppe: ['boots'],
      },
      {
        id: 6,
        emoji: '🚜⚙️',
        en: 'Follow safe operating procedures for harvesting machinery',
        hi: 'कटाई मशीनरी को सही तरीके से चलाने के नियम अपनाएं',
        ppe: ['helmet', 'gloves'],
      },
      {
        id: 7,
        emoji: '🌾😷',
        en: 'Wear mask during grain threshing to prevent dust inhalation',
        hi: 'दाने की मड़ाई के समय धूल से बचने के लिए मास्क पहनें',
        ppe: ['mask'],
      },
      {
        id: 8,
        emoji: '🩹🧰',
        en: 'Keep first aid kit at the harvesting site',
        hi: 'कटाई वाली जगह पर प्राथमिक चिकित्सा किट रखें',
        ppe: [],
      },
      {
        id: 9,
        emoji: '🚛📦',
        en: 'Load and transport harvested crop safely — do not overload vehicles',
        hi: 'कटी फसल को सुरक्षित लादें और ले जाएं — वाहन पर अधिक भार न डालें',
        ppe: ['gloves'],
      },
      {
        id: 10,
        emoji: '🧹🔐',
        en: 'Clean and store all tools and equipment properly after use',
        hi: 'काम के बाद सभी औज़ार और उपकरण साफ़ करके सही जगह रखें',
        ppe: [],
      },
    ],
  },
  {
    id: 'irrigation',
    icon: 'irrigation',
    title: { en: 'Irrigation & Well Safety', hi: 'सिंचाई और कुआं सुरक्षा' },
    description: {
      en: 'Safety precautions for pump operation, wells, and water channels',
      hi: 'पंप संचालन, कुएं और नहरों के लिए सुरक्षा सावधानियां',
    },
    estimatedMinutes: 12,
    items: [
      {
        id: 1,
        emoji: '🔌🔍',
        en: 'Inspect pump motor and all electrical connections before switching on',
        hi: 'चालू करने से पहले पंप मोटर और सभी बिजली के कनेक्शन जांचें',
        ppe: ['boots'],
      },
      {
        id: 2,
        emoji: '⚡💧',
        en: 'Check for exposed or damaged wires near water — repair immediately',
        hi: 'पानी के पास खुले या कटे तारों की जांच करें — तुरंत ठीक कराएं',
        ppe: ['boots', 'gloves'],
      },
      {
        id: 3,
        emoji: '🖐️🚫',
        en: 'Never touch electrical equipment with wet hands',
        hi: 'गीले हाथों से बिजली के उपकरण कभी न छुएं',
        ppe: ['gloves'],
      },
      {
        id: 4,
        emoji: '⏚🔧',
        en: 'Ensure proper earthing/grounding of pump motor',
        hi: 'पंप मोटर की अर्थिंग (ग्राउंडिंग) सही है सुनिश्चित करें',
        ppe: [],
      },
      {
        id: 5,
        emoji: '👶🚧',
        en: 'Keep children and animals away from open wells and canals',
        hi: 'खुले कुएं और नहरों से बच्चों और जानवरों को दूर रखें',
        ppe: [],
      },
      {
        id: 6,
        emoji: '🧱🛡️',
        en: 'Install safety barriers or walls around open wells',
        hi: 'खुले कुओं के चारों ओर सुरक्षा दीवार या जाली लगाएं',
        ppe: [],
      },
      {
        id: 7,
        emoji: '🔎🌊',
        en: 'Check water channels for cracks and structural damage',
        hi: 'पानी की नालियों में दरार और टूट-फूट की जांच करें',
        ppe: ['boots'],
      },
      {
        id: 8,
        emoji: '🌊⚠️',
        en: 'Monitor for waterlogging — be alert to drowning hazards',
        hi: 'जलभराव पर नज़र रखें — डूबने के ख़तरे से सावधान रहें',
        ppe: ['boots'],
      },
      {
        id: 9,
        emoji: '⛽🔒',
        en: 'Store diesel/fuel for pumps safely — away from ignition sources',
        hi: 'पंप का डीज़ल/ईंधन सुरक्षित रखें — आग के स्रोतों से दूर',
        ppe: [],
      },
      {
        id: 10,
        emoji: '🆘📞',
        en: 'Know emergency plan if someone falls into a well or canal',
        hi: 'कुएं या नहर में कोई गिर जाए तो आपातकालीन योजना जानें',
        ppe: [],
      },
    ],
  },
  {
    id: 'chemical-storage',
    icon: 'chemical',
    title: { en: 'Chemical & Fertilizer Storage', hi: 'रासायनिक और उर्वरक भंडारण' },
    description: {
      en: 'Safe storage practices for pesticides, fertilizers, and farm chemicals',
      hi: 'कीटनाशक, उर्वरक और कृषि रसायनों के सुरक्षित भंडारण की जांच सूची',
    },
    estimatedMinutes: 10,
    items: [
      {
        id: 1,
        emoji: '🏷️📦',
        en: 'Store all chemicals in their original labeled containers only',
        hi: 'सभी रसायनों को उनके मूल लेबल वाले डिब्बों में ही रखें',
        ppe: ['gloves'],
      },
      {
        id: 2,
        emoji: '🔐👶',
        en: 'Keep storage area locked — away from children and animals',
        hi: 'भंडारण क्षेत्र में ताला लगाएं — बच्चों और जानवरों से दूर रखें',
        ppe: [],
      },
      {
        id: 3,
        emoji: '🌬️🪟',
        en: 'Ensure proper ventilation in the chemical storage room',
        hi: 'रसायन भंडारण कक्ष में हवा का उचित आवागमन सुनिश्चित करें',
        ppe: [],
      },
      {
        id: 4,
        emoji: '⚠️🔀',
        en: 'Keep pesticides separate from fertilizers, seeds, and food items',
        hi: 'कीटनाशकों को उर्वरक, बीज और खाद्य पदार्थों से अलग रखें',
        ppe: [],
      },
      {
        id: 5,
        emoji: '📅🗑️',
        en: 'Check expiry dates — dispose of expired chemicals safely',
        hi: 'एक्सपायरी डेट जांचें — पुराने रसायनों को सुरक्षित तरीके से नष्ट करें',
        ppe: ['gloves', 'mask'],
      },
      {
        id: 6,
        emoji: '🧤📄',
        en: 'Always wear gloves when handling chemical containers',
        hi: 'रासायनिक डिब्बों को हमेशा दस्ताने पहनकर ही छुएं',
        ppe: ['gloves', 'goggles'],
      },
      {
        id: 7,
        emoji: '📋🆘',
        en: 'Keep safety data sheets (MSDS) accessible near storage',
        hi: 'सुरक्षा डेटा शीट (MSDS) भंडारण के पास उपलब्ध रखें',
        ppe: [],
      },
      {
        id: 8,
        emoji: '🧹🧽',
        en: 'Keep spill cleanup materials (sand, absorbent) nearby',
        hi: 'रिसाव साफ़ करने का सामान (रेत, सोखने वाला कपड़ा) पास रखें',
        ppe: ['gloves', 'boots'],
      },
      {
        id: 9,
        emoji: '🚭🔥',
        en: 'No smoking or open flames near chemical storage area',
        hi: 'रसायन भंडारण के पास धूम्रपान या खुली आग सख़्त मना है',
        ppe: [],
      },
      {
        id: 10,
        emoji: '📞🏥',
        en: 'Post emergency contact numbers and poison control at storage entrance',
        hi: 'भंडारण के प्रवेश पर आपातकालीन नंबर और विष नियंत्रण नंबर लगाएं',
        ppe: [],
      },
    ],
  },
  {
    id: 'livestock',
    icon: 'livestock',
    title: { en: 'Livestock Handling Safety', hi: 'पशुधन संभालने की सुरक्षा' },
    description: {
      en: 'Safety checklist for handling cattle, buffaloes, and farm animals',
      hi: 'गाय, भैंस और खेती के जानवरों को संभालने की सुरक्षा जांच सूची',
    },
    estimatedMinutes: 12,
    items: [
      {
        id: 1,
        emoji: '🐄🤚',
        en: 'Approach animals calmly from the side — never from directly behind',
        hi: 'जानवरों के पास शांति से बगल से जाएं — कभी सीधे पीछे से न जाएं',
        ppe: [],
      },
      {
        id: 2,
        emoji: '🥾👕',
        en: 'Wear sturdy boots and protective clothing while handling animals',
        hi: 'जानवरों को संभालते समय मज़बूत जूते और सुरक्षित कपड़े पहनें',
        ppe: ['boots', 'coverall'],
      },
      {
        id: 3,
        emoji: '🐃🔍',
        en: 'Check animal health and mood before handling — look for aggression signs',
        hi: 'संभालने से पहले जानवर की सेहत और मिज़ाज जांचें — आक्रामकता के संकेत देखें',
        ppe: [],
      },
      {
        id: 4,
        emoji: '🔗🛡️',
        en: 'Use proper restraining equipment — ropes, halters, crush gates',
        hi: 'सही बांधने के उपकरण इस्तेमाल करें — रस्सी, नकेल, पिंजरा',
        ppe: ['gloves'],
      },
      {
        id: 5,
        emoji: '🧹🚫',
        en: 'Ensure ground is clean and non-slippery to prevent falls',
        hi: 'ज़मीन साफ़ और फिसलन रहित हो — गिरने से बचाव करें',
        ppe: ['boots'],
      },
      {
        id: 6,
        emoji: '💉🧤',
        en: 'Wear gloves during vaccination, medication, and wound treatment',
        hi: 'टीकाकरण, दवाई और घाव के इलाज के समय दस्ताने पहनें',
        ppe: ['gloves'],
      },
      {
        id: 7,
        emoji: '🍶🥣',
        en: 'Follow safe feeding practices — maintain distance during feeding',
        hi: 'सुरक्षित चारा देने के तरीके अपनाएं — खिलाते समय दूरी बनाएं',
        ppe: [],
      },
      {
        id: 8,
        emoji: '🚪🔩',
        en: 'Check fencing and gate latches regularly for damage',
        hi: 'बाड़ और दरवाज़ों की कुंडी की नियमित जांच करें',
        ppe: ['gloves'],
      },
      {
        id: 9,
        emoji: '🧼♻️',
        en: 'Maintain hygiene — wash hands after handling, manage animal waste',
        hi: 'सफ़ाई रखें — संभालने के बाद हाथ धोएं, गोबर-मूत्र का प्रबंधन करें',
        ppe: ['gloves', 'boots'],
      },
      {
        id: 10,
        emoji: '⚠️🐂',
        en: 'Know animal warning signs — raised tail, pinned ears, stomping hooves',
        hi: 'जानवर के ख़तरे के संकेत जानें — उठी पूंछ, दबे कान, पैर पटकना',
        ppe: [],
      },
    ],
  },
  {
    id: 'electrical',
    icon: 'electrical',
    title: { en: 'Farm Electrical Safety', hi: 'खेत बिजली सुरक्षा' },
    description: {
      en: 'Electrical safety checks for farm wiring, motors, and equipment',
      hi: 'खेत की बिजली तारों, मोटर और उपकरणों की सुरक्षा जांच सूची',
    },
    estimatedMinutes: 10,
    items: [
      {
        id: 1,
        emoji: '🔌🔍',
        en: 'Inspect all wiring and connections — look for wear, cracks, or burns',
        hi: 'सभी तारों और कनेक्शन जांचें — घिसाव, दरार या जलने के निशान देखें',
        ppe: ['gloves', 'boots'],
      },
      {
        id: 2,
        emoji: '⚡🚫',
        en: 'Never use damaged cables or wires with exposed copper',
        hi: 'कटे-छिले तार या खुले तांबे वाली केबल कभी इस्तेमाल न करें',
        ppe: [],
      },
      {
        id: 3,
        emoji: '⏚✅',
        en: 'Verify proper earthing of all electrical motors and equipment',
        hi: 'सभी बिजली की मोटर और उपकरणों की अर्थिंग सही है जांचें',
        ppe: ['gloves', 'boots'],
      },
      {
        id: 4,
        emoji: '🔲🛡️',
        en: 'Install MCB/RCCB circuit breakers for overload and shock protection',
        hi: 'ओवरलोड और करंट से बचाव के लिए MCB/RCCB लगाएं',
        ppe: [],
      },
      {
        id: 5,
        emoji: '📦☔',
        en: 'Keep electrical panels dry, covered, and protected from rain',
        hi: 'बिजली के पैनल सूखे, ढके और बारिश से सुरक्षित रखें',
        ppe: [],
      },
      {
        id: 6,
        emoji: '🔌⚖️',
        en: 'Do not overload circuits — use correct rated fuses and wires',
        hi: 'सर्किट पर अधिक भार न डालें — सही क्षमता के फ्यूज़ और तार लगाएं',
        ppe: [],
      },
      {
        id: 7,
        emoji: '🔗🚫',
        en: 'Use proper rated extension cords — no makeshift wire connections',
        hi: 'सही क्षमता के एक्सटेंशन कॉर्ड इस्तेमाल करें — जुगाड़ वाले तार न लगाएं',
        ppe: [],
      },
      {
        id: 8,
        emoji: '🔴🔧',
        en: 'Turn off main power supply before any repair or maintenance work',
        hi: 'कोई भी मरम्मत करने से पहले मुख्य बिजली सप्लाई बंद करें',
        ppe: ['gloves', 'boots'],
      },
      {
        id: 9,
        emoji: '⚠️🏷️',
        en: 'Mark high voltage areas with clear warning signs',
        hi: 'हाई वोल्टेज वाले क्षेत्रों पर चेतावनी के बोर्ड लगाएं',
        ppe: [],
      },
      {
        id: 10,
        emoji: '🆘⚡',
        en: 'Know how to safely disconnect power in an emergency — use dry wooden stick',
        hi: 'आपात स्थिति में बिजली सुरक्षित काटना जानें — सूखी लकड़ी की छड़ी इस्तेमाल करें',
        ppe: [],
      },
    ],
  },
  {
    id: 'heat-stress',
    icon: 'heatstress',
    title: { en: 'Heat Stress Prevention', hi: 'लू और गर्मी से बचाव' },
    description: {
      en: 'Protect yourself and workers from heat stroke during summer farm work',
      hi: 'गर्मियों में खेती के काम के दौरान लू और हीट स्ट्रोक से बचाव की जांच सूची',
    },
    estimatedMinutes: 10,
    items: [
      {
        id: 1,
        emoji: '🌅⏰',
        en: 'Start work early morning — avoid outdoor work between 11 AM and 3 PM',
        hi: 'सुबह जल्दी काम शुरू करें — दोपहर 11 बजे से 3 बजे तक बाहर काम न करें',
        ppe: [],
      },
      {
        id: 2,
        emoji: '👕🤍',
        en: 'Wear light-colored, loose cotton clothing and a wide-brim hat',
        hi: 'हल्के रंग के ढीले सूती कपड़े और चौड़ी टोपी पहनें',
        ppe: ['helmet'],
      },
      {
        id: 3,
        emoji: '💧⏱️',
        en: 'Drink water every 15-20 minutes — do not wait until thirsty',
        hi: 'हर 15-20 मिनट में पानी पिएं — प्यास लगने का इंतज़ार न करें',
        ppe: [],
      },
      {
        id: 4,
        emoji: '🧂🥤',
        en: 'Carry ORS (oral rehydration solution) or nimbu-pani with salt',
        hi: 'ORS (ओआरएस) या नमक-नींबू पानी साथ रखें',
        ppe: [],
      },
      {
        id: 5,
        emoji: '🌳😌',
        en: 'Take rest breaks every 30 minutes in shade — cool down before resuming',
        hi: 'हर 30 मिनट में छाया में आराम करें — ठंडा होकर ही काम शुरू करें',
        ppe: [],
      },
      {
        id: 6,
        emoji: '🤕⚠️',
        en: 'Watch for danger signs: dizziness, headache, nausea, muscle cramps',
        hi: 'ख़तरे के संकेत पहचानें: चक्कर, सिरदर्द, उल्टी, मांसपेशियों में ऐंठन',
        ppe: [],
      },
      {
        id: 7,
        emoji: '👶👴',
        en: 'Never leave children or elderly in direct sunlight while working',
        hi: 'काम करते समय बच्चों या बुज़ुर्गों को सीधी धूप में न छोड़ें',
        ppe: [],
      },
      {
        id: 8,
        emoji: '🩹🧊',
        en: 'Keep first aid kit with cold water, wet towels, and ice packs',
        hi: 'प्राथमिक चिकित्सा किट में ठंडा पानी, गीला तौलिया और बर्फ़ रखें',
        ppe: [],
      },
      {
        id: 9,
        emoji: '🏥📍',
        en: 'Know the nearest medical facility and its contact number',
        hi: 'नज़दीकी अस्पताल का पता और फ़ोन नंबर जानें',
        ppe: [],
      },
      {
        id: 10,
        emoji: '🆘🚑',
        en: 'Heat stroke emergency: move to shade, pour cold water, call ambulance',
        hi: 'लू लगने पर: छाया में ले जाएं, ठंडा पानी डालें, एम्बुलेंस बुलाएं',
        ppe: [],
      },
    ],
  },
]

export default TEMPLATES
